# site information
name: "jjgrainger"
description: "Web Developer, Falmouth, Cornwall, UK"
baseurl: ""
url: "http://jjgrainger.co.uk"
permalink: /:year/:month/:day/:title/

# build configuration
sass:
  style: compressed

feed:
  path: atom.xml

# add project collection
collections:
  projects:
    output: true

# use rouge for syntax highlighting
markdown: kramdown
highlighter: rouge

# author information
author: "jjgrainger"
author_email: "joe@jjgrainger.co.uk"

plugins:
  - jekyll-feed

# ingore files on build
exclude:
  - 'README.md'
